sudo: required
services:
  - docker
before_install:
  - docker build -t ranjithcheguri/docker-react-express-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run ranjithcheguri/docker-react-express-test npm test -- --coverage 

after_success:
  - docker build -t ranjithcheguri/docker-react-express-client ./client/
  - docker build -t ranjithcheguri/docker-react-express-server ./server/
  - docker build -t ranjithcheguri/docker-react-express-nginx ./nginx/
  - docker build -t ranjithcheguri/docker-react-express-worker ./worker/

  # Login to docker CLI, ID,password are stored in travis website environmental variables

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub

  - docker push ranjithcheguri/docker-react-express-client
  - docker push ranjithcheguri/docker-react-express-server
  - docker push ranjithcheguri/docker-react-express-nginx
  - docker push ranjithcheguri/docker-react-express-worker  
